Repository citycoins/citycoin, pull requests merged in 2021-05, with the labels that each got.

#26 Remove redundant `asserts!`
  contracts/citycoin.clar
Labels: Low, QOL

#36 Feature: add mining activation threshold and miners registration mechanism
  contracts/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
Labels: High

#35 Add minting schedule
  citycoin-prd.md
  contracts/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
Labels: High

#43 Optimize mine-tokens execution costs
  contracts/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
  tests/test-poxl.clar
Labels: High, enhancement

#44 Optimize claim-token-reward execution costs
  contracts/citycoin.clar
  contracts/test_addons/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
Labels: Help!, High, enhancement

#45 Split miner rewards v2
  contracts/citycoin.clar
  contracts/test_addons/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
Labels: High, enhancement

#47 Feat pushing miners out of the list and increasing max number of miners to 128
  contracts/citycoin.clar
  contracts/test_addons/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
Labels: Design, Help!, High, enhancement

#62 Feat/data structure remodel
  contracts/citycoin.clar
  contracts/test_addons/citycoin.clar
  src/citycoin-client.ts
  tests/citycoin_test.ts
Labels: Help!, High, enhancement
